// <auto-generated />
using System;
using HandlelisteData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandlelisteData.Migrations
{
    [DbContext(typeof(HandlelisteContext))]
    [Migration("20230417101457_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandlelisteDomain.Handleliste", b =>
                {
                    b.Property<int>("HandlelisteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HandlelisteId"));

                    b.Property<string>("HandlelisteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HandlelisteId");

                    b.ToTable("Handlelister");
                });

            modelBuilder.Entity("HandlelisteDomain.Vare", b =>
                {
                    b.Property<int>("VareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VareId"));

                    b.Property<int?>("HandlelisteId")
                        .HasColumnType("int");

                    b.Property<string>("VareName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VareId");

                    b.HasIndex("HandlelisteId");

                    b.ToTable("Varer");
                });

            modelBuilder.Entity("HandlelisteDomain.Vare", b =>
                {
                    b.HasOne("HandlelisteDomain.Handleliste", null)
                        .WithMany("Varer")
                        .HasForeignKey("HandlelisteId");
                });

            modelBuilder.Entity("HandlelisteDomain.Handleliste", b =>
                {
                    b.Navigation("Varer");
                });
#pragma warning restore 612, 618
        }
    }
}
